import localFont from "next/font/local";
import "./globals.css";

 
const bebas_neue = localFont({
  src: "./fonts/BebasNeue-Regular.ttf",
  variable: "--font-bebas-neue",
  subsets: ["latin"],
})

const sf_pro = localFont({
  src: [
    {
      path: './fonts/SF-Pro-Display-Regular.ttf',
      weight: '400',
      style: 'normal',
    },  
    {
      path: './fonts/SF-Pro-Display-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/SF-Pro-Display-Bold.ttf',
      weight: '800',
      style: 'normal',
    }
  ],
  variable: '--font-sf-pro'
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bebas_neue.variable} ${sf_pro.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
